<?php
/**
 * @version 8.0 [rev.8.0.01]
 */

/* @var string $gatewayMessage */
?>

<p>
    <?php echo $this->_("Your payment hasn't been registered, or was invalid."); ?>
</p>
<p>
    <?php echo $this->_('Sorry for the inconvenience.'); ?>
</p>

<?php if (!empty($gatewayMessage)) { ?>
    <h6><?php echo $this->_('Message from Payment Gateway:'); ?></h6>
    <div class="text-danger"><?php echo $gatewayMessage; ?></div>
<?php } ?>

