<?php
/**
 * @version 8.0 [rev.8.0.01]
 */
?>

<div class="cookie-usage bg-dark text-light py-2">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm">
                <small><?php echo $this->_($this->cookieUsageMessage); ?></small>
            </div>
            <div class="col-12 col-sm-auto">
                <button class="btn btn-sm btn-primary btn-cookie-confirm"><?php echo $this->_('I Understand'); ?></button>
            </div>
        </div>
    </div>
</div>