<?php
/**
 * @version 8.0 [rev.8.0.01]
 */
?>
<div>
    <?php echo sprintf(
        $this->_('Your account details on %s are:'),
        $this->siteName); ?>
</div>
<ul>
    <li>
        <?php echo $this->_('Username:'); ?>
        <b><?php echo $this->data['user']['username']; ?></b>
    </li>
    <li>
        <?php echo $this->_('Password: - hidden -'); ?>
    </li>
</ul>
<p>
    <?php echo $this->_('Please'); ?>
    [ <a href="<?php echo $this->sitePath . $this->url(null, 'members-sign-in', false, null, false); ?>">
        <?php echo $this->_('click here'); ?>
    </a> ]
    <?php echo $this->_('to sign in.'); ?>
</p>
<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>
