<?php
/**
 * @version 8.1 [rev.8.1.01]
 */

$listing = $this->data['listing'];
?>
<p><?php echo sprintf(
        $this->_('You have received a new message in your inbox on %s.'),
        $this->siteName); ?></p>

<?php if ($listing instanceof \Ppb\Db\Table\Row\Listing) { ?>
    <div class="my-4">
        <?php echo $this->listing($listing, 'partials/listing-list.phtml')
            ->setDisplaySeller()
            ->setDisplayEnhanced()
            ->render(array(
                'email'    => true,
                'sitePath' => $this->sitePath,
            )); ?>
    </div>
<?php } ?>

<dl class="dl-lg dl-indented">
    <dt>
        <?php echo $this->_('Sender:'); ?>
    </dt>
    <dd>
        <span class="text-success"><?php echo $this->data['username']; ?></span>
    </dd>
    <dt>
        <span><?php echo $this->_('Title:'); ?></span>
    </dt>
    <dd>
        <em><?php echo $this->renderText($this->data['title']); ?></em>
    </dd>
    <dt>
        <?php echo $this->_('Message:'); ?>
    </dt>
    <dd>
        <?php echo $this->renderText($this->data['message'], true); ?>
    </dd>
</dl>
<p>
    [ <a href="<?php echo $this->sitePath . $this->url($this->data['link'], null, false, null, false); ?>">
        <?php echo $this->_('Click here'); ?>
    </a> ]
    <?php echo $this->_('to reply.'); ?>
</p>
<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>
