<?php
/**
 * @version 8.0 [rev.8.0.01]
 */

$listing = $this->data['listing'];
?>

<h5 class="text-center">
    <?php echo sprintf(
        $this->_('A new listing has been added in one of your favorite stores on %s.'),
        $this->siteName); ?>
</h5>

<div class="my-4">
    <?php echo $this->listing($listing, 'partials/listing-list.phtml')
        ->setDisplaySeller()
        ->setDisplayEnhanced()
        ->render(array(
            'email'    => true,
            'sitePath' => $this->sitePath,
        )); ?>
</div>

<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>

