<?php
/**
 * @version 8.0 [rev.8.0.01]
 */
?>
<h4>
    <?php echo $this->_('Thank you for registering.'); ?>
</h4>
<p>
    <?php echo $this->_('Your account has been approved successfully.'); ?>
</p>

<div><?php echo $this->_('Your login details are:'); ?></div>
<ul>
    <li>
        <?php echo $this->_('Username:'); ?>
        <b><?php echo $this->data['username']; ?></b>
    </li>
    <li>
        <?php echo $this->_('Email:'); ?>
        <b><?php echo $this->data['email']; ?></b>
    </li>
</ul>
<p>
    <?php echo $this->_('Please'); ?>
    [ <a href="<?php echo $this->sitePath . $this->url(null, 'members-sign-in', false, null, false); ?>">
        <?php echo $this->_('click here'); ?>
    </a> ]
    <?php echo $this->_('to sign in.'); ?>
</p>
<p>
    <?php echo $this->_('Best regards'); ?> <br>
    <?php echo $this->siteName; ?>
</p>
