<?php
/**
 * MOD:- CURRENCY SELECTOR
 */
?>
<div class="dropdown currency-selector-dropdown">
    <button class="btn dropdown-toggle" type="button" id="currencySelectorDropdown" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="true">
        <span class="badge badge-text badge-slim"><?php echo $this->activeCurrency; ?></span>
    </button>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="currencySelectorDropdown">
        <?php foreach ($this->currencies as $key => $currency) { ?>
            <div class="my-1">
                <a href="<?php echo $this->url(array('selected_currency' => $key), null, true); ?>">
                    <span class="badge badge-text badge-slim"><?php echo (!empty($currency['symbol'])) ? $currency['symbol'] : $currency['iso_code']; ?></span>
                    <?php echo $currency['description']; ?>
                </a>
            </div>
        <?php } ?>
    </div>
</div>
