<?php
/**
 * MOD:- SELLERS CREDIT
 */
/* @var array $totals */

$headlineButtons = null;

$container = $this->navigation()->getInitialContainer()
    ->findOneBy('label', $this->_('Balance Withdrawals Filter'));

$headlineButtons .= $this->navigation($container, 'navigation/browse-filter.phtml')->menu();

$this->setGlobal('headlineButtons', $headlineButtons);

/** @var \Ppb\Form\Element\DateTime $dateTimeFrom */
$dateTimeFrom = $this->formElement('\Ppb\Form\Element\DateTime', 'date_from', $this->dateFrom)
    ->setAttributes(array(
        'placeholder' => $this->_('From..'),
        'class'       => 'form-control input-default'
    ))
    ->setCustomData(array(
        'formData' => array(
            'format'     => '"YYYY-MM-DD HH:mm"',
            'maxDate'    => 'new Date()',
            'useCurrent' => 'false',
            'stepping'   => '5',
            'showClear'  => 'true',
        ),
    ));

/** @var \Ppb\Form\Element\DateTime $dateTimeTo */
$dateTimeTo = $this->formElement('\Ppb\Form\Element\DateTime', 'date_to', $this->dateTo)
    ->setAttributes(array(
        'placeholder' => $this->_('To..'),
        'class'       => 'form-control input-default'
    ))
    ->setCustomData(array(
        'formData' => array(
            'format'     => '"YYYY-MM-DD HH:mm"',
            'maxDate'    => 'new Date()',
            'useCurrent' => 'false',
            'stepping'   => '5',
            'showClear'  => 'true',
        ),
    ));

$this->script()->addBodyCode(
    $dateTimeFrom->getBodyCode());
$this->script()->addBodyCode(
    $dateTimeTo->getBodyCode());

?>

<nav class="navbar p-0 mb-4">
    <form class="form-inline ml-auto" action="" method="get">
        <?php echo $this->formElement('hidden', 'filter', $this->filter)->render(); ?>

        <?php echo $dateTimeFrom->render(); ?>
        <?php echo $dateTimeTo->render(); ?>

        <?php echo $this->formElement('submit', 'submit', $this->_('Show'))
            ->setAttributes(array('class' => 'btn btn-secondary'))
            ->render();
        ?>
    </form>
</nav>

<p class="text-right">
    <span class="badge badge-info">
        <?php echo $this->_('Pending:'); ?>
        <?php echo $this->amount($totals['pending'], null, null, true); ?>
    </span>
    <span class="badge badge-success">
        <?php echo $this->_('Paid:'); ?>
        <?php echo $this->amount($totals['paid'], null, null, true); ?>
    </span>
    <span class="badge badge-danger">
        <?php echo $this->_('Declined:'); ?>
        <?php echo $this->amount($totals['declined'], null, null, true); ?>
    </span>
    <span class="badge badge-warning">
        <?php echo $this->_('Cancelled:'); ?>
        <?php echo $this->amount($totals['cancelled'], null, null, true); ?>
    </span>
</p>

<div class="table-responsive">
    <table class="table table-hover">
        <caption>
            <?php echo sprintf(
                $this->pluralize(
                    $count = $this->paginator->getPages()->totalItemCount,
                    $this->_('<strong>%s</strong> result found.'),
                    $this->_('<strong>%s</strong> results found.')
                ), $count); ?>

            <?php if ($this->paginator->getPages()->totalItemCount > 1) { ?>
                <?php echo sprintf(
                    $this->_('Showing results <strong>%s</strong> to <strong>%s</strong>'),
                    $this->paginator->getPages()->firstItemNumber,
                    $this->paginator->getPages()->lastItemNumber); ?>
            <?php } ?>
        </caption>
        <?php if ($this->paginator->getPages()->totalItemCount) { ?>
            <thead class="thead-light">
            <tr>
                <th><?php echo $this->_('Request Details'); ?></th>
                <th class="size-small"><?php echo $this->_('Req. Date'); ?></th>
                <th class="size-actions"><?php echo $this->_('Actions'); ?></th>
            </tr>
            </thead>
        <?php } ?>
        <tbody>
        <?php
        /** @var \Ppb\Db\Table\Row\BalanceWithdrawal $withdrawal */
        foreach ($this->paginator as $withdrawal) {
            /** @var \Ppb\Db\Table\Row\User $user */
            $user = $withdrawal->findParentRow('\Ppb\Db\Table\Users');
            ?>
            <tr>
                <td>
                    <dl class="dl-variable">
                        <?php if ($inAdmin) { ?>
                            <dt>
                                <span><?php echo $this->_('Username'); ?></span>
                            </dt>
                            <dd><?php echo $this->userDetails($user)->display(); ?></dd>
                        <?php } ?>
                        <dt>
                            <span><?php echo $this->_('Amount'); ?></span>
                        </dt>
                        <dd><?php echo $this->amount(abs($withdrawal['amount']), $withdrawal['currency']); ?></dd>

                        <dt>
                            <span><?php echo $this->_('Status'); ?></span>
                        </dt>
                        <dd><?php echo $this->balanceWithdrawal($withdrawal)->status(); ?></dd>
                    </dl>
                </td>
                <td>
                    <small><?php echo $this->date($withdrawal['created_at']); ?></small>
                </td>
                <td>
                    <?php if ($withdrawal->canAccept()) { ?>
                        <a class="btn btn-success mb-1 confirm-box"
                           href="<?php echo $this->url(array('option' => 'accept', 'id' => $withdrawal['id'])); ?>"
                           title="<?php echo $this->_('Accept / Mark As Paid'); ?>"
                           data-message="<?php echo $this->_('Are you sure you want to accept / mark as paid this withdrawal request?'); ?>">
                            <span data-feather="check"></span>
                            <?php echo $this->_('Accept'); ?>
                        </a>
                    <?php } ?>
                    <?php if ($withdrawal->canDecline()) { ?>
                        <a class="btn btn-danger mb-1 confirm-box"
                           href="<?php echo $this->url(array('option' => 'decline', 'id' => $withdrawal['id'])); ?>"
                           title="<?php echo $this->_('Decline Withdrawal Request'); ?>"
                           data-message="<?php echo $this->_('Are you sure you want to decline this withdrawal request?'); ?>">
                            <span data-feather="x"></span>
                            <?php echo $this->_('Decline'); ?>
                        </a>
                    <?php } ?>
                    <?php if ($withdrawal->canCancel()) { ?>
                        <a class="btn btn-warning mb-1 confirm-box"
                           href="<?php echo $this->url(array('option' => 'cancel', 'id' => $withdrawal['id'])); ?>"
                           title="<?php echo $this->_('Cancel Withdrawal Request'); ?>"
                           data-message="<?php echo $this->_('Are you sure you want to cancel this withdrawal request?'); ?>">
                            <span data-feather="x"></span>
                            <?php echo $this->_('Cancel'); ?>
                        </a>
                    <?php } ?>
                    <?php if ($withdrawal->canDelete()) { ?>
                        <a class="btn btn-dark mb-1 confirm-box"
                           href="<?php echo $this->url(array('option' => 'delete', 'id' => $withdrawal['id'])); ?>"
                           title="<?php echo $this->_('Delete Withdrawal Request'); ?>"
                           data-message="<?php echo $this->_('Are you sure you want to delete this withdrawal request?'); ?>">
                            <span data-feather="x"></span>
                            <?php echo $this->_('Delete'); ?>
                        </a>
                    <?php } ?>

                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<?php echo $this->pagination($this->paginator, 'sliding', 'partials/pagination.phtml'); ?>

