<?php
/**
 * MOD:- BANK TRANSFER
 */

$headlineButtons = null;

$headlineButtons .= '<a class="btn btn-outline-secondary" '
    . 'href="' . $this->url(array('action' => 'add-bank-account')) . '">'
    . $this->_('Add Bank Account') . '</a>';
?>

<?php
echo $this->navigation()->setPartial('navigation/headline.phtml')->headline(array(
    'headline'        => '',
    'headlineButtons' => $headlineButtons,
));
?>

<div class="table-responsive">
    <table class="table table-hover">
        <caption>
            <?php echo sprintf(
                $this->pluralize(
                    $count = $this->paginator->getPages()->totalItemCount,
                    $this->_('<strong>%s</strong> bank account found.'),
                    $this->_('<strong>%s</strong> bank accounts found.')
                ), $count); ?>

            <?php if ($this->paginator->getPages()->totalItemCount > 1) { ?>
                <?php echo sprintf(
                    $this->_('Showing results <strong>%s</strong> to <strong>%s</strong>'),
                    $this->paginator->getPages()->firstItemNumber,
                    $this->paginator->getPages()->lastItemNumber); ?>
            <?php } ?>
        </caption>
        <?php if ($this->paginator->getPages()->totalItemCount) { ?>
            <thead class="thead-light">
            <tr>
                <th><?php echo $this->_('Details'); ?></th>
                <th class="size-actions"><?php echo $this->_('Actions'); ?></th>
            </tr>
            </thead>
        <?php } ?>
        <tbody>
        <?php
        /** @var \Ppb\Db\Table\Row\BankAccount $bankAccount */
        foreach ($this->paginator as $bankAccount) {
            ?>

            <tr>
                <td>
                    <?php echo $this->bankAccount($bankAccount)->display(); ?>
                </td>
                <td>
                    <?php if ($bankAccount->canEdit()) { ?>
                        <a class="btn btn-secondary mb-1"
                           href="<?php echo $this->url(array('action' => 'edit-bank-account', 'id' => $bankAccount['id'])); ?>"
                           title="<?php echo $this->_('Edit Bank Account'); ?>">
                            <span data-feather="folder"></span>
                            <?php echo $this->_('Edit'); ?>
                        </a>
                    <?php } ?>
                    <?php if ($bankAccount->canDelete()) { ?>
                        <a class="btn btn-danger mb-1 confirm-box"
                           href="<?php echo $this->url(array('action' => 'delete-bank-account', 'id' => $bankAccount['id']), null, true); ?>"
                           title="<?php echo $this->_('Delete Bank Account'); ?>"
                           data-message="<?php echo $this->_('Are you sure you want to remove this bank account?'); ?>">
                            <span data-feather="x"></span>
                            <?php echo $this->_('Delete'); ?>
                        </a>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<?php echo $this->pagination($this->paginator, 'sliding', 'partials/pagination.phtml'); ?>

