<?php
/**
 * @version 8.0 [rev.8.0.03]
 */

/* @var \Ppb\Db\Table\Row\ContentSection $section */
/* @var \Ppb\Db\Table\Row\ContentEntry $entry */
/* @var \Ppb\Navigation\Page\ContentSection $currentPage */
/* @var bool $inAdmin */

$headlineButtons = null;

if ($inAdmin) {
    if ($sectionEntryStatus = $this->sectionEntryStatus($section, $entry)) {
        $headlineButtons = '<div class="mb-1 text-right">' . $sectionEntryStatus . '</div>';
    }
} ?>

<?php
if ($currentPage) {
    echo $this->navigation()
        ->setContainer($currentPage)
        ->setPartial('navigation/breadcrumbs.phtml')->setMinDepth(0)->breadcrumbs(array(
            'home' => array(
                'params' => array('module' => 'app', 'controller' => 'index', 'action' => 'index'),
                'label'  => $this->_('Home'),
            ),
            'end'  => array(
                'params' => $entry->link(),
                'label'  => $entry['title'],
            )
        ));
}
?>

<?php
echo $this->navigation()->setPartial('navigation/headline.phtml')->headline(array(
    'headline'        => $entry['title'],
    'headlineButtons' => $headlineButtons,
));
?>

<?php echo $this->renderHtml($entry['content'], true); ?>
