<?php
/**
 * @version 8.1 [rev.8.1.01]
 */
$requirementsMet = true;
$mysqlInfo = 'n/a';
$mysqlVersion = 0;

if (function_exists('mysqli_get_client_info')) {
    $mysqlInfo = @mysqli_get_client_info();
    $mysqlVersion = @mysqli_get_client_version();
}
?>

<div class="alert alert-primary">
    This process will install PHP Pro Bid on your server. <br>To proceed, please complete the data requested in by the
    fields below.
</div>
<h5 class="subtitle">
    Server Requirements
</h5>

<dl class="dl-indented">
    <dt>mySQL 5.1 (5.5 recommended) / MariaDB</dt>
    <dd>
        <span class="badge badge-info"><?php echo $mysqlInfo; ?></span>
    </dd>
    <dt>PDO Library w/ MySQL Driver</dt>
    <dd>
        <div>
            <?php
            if (extension_loaded('pdo_mysql')) {
                echo '<span class="badge badge-success">Enabled</span>';
            }
            else {
                $requirementsMet = false;
                echo '<span class="badge badge-danger">Disabled</span>';
            } ?>
        </div>
    </dd>
    <dt>GD Library</dt>
    <dd>
        <div>
            <?php
            if (extension_loaded('gd') && function_exists('gd_info')) {
                echo '<span class="badge badge-success">Enabled</span>';
            }
            else {
                $requirementsMet = false;
                echo '<span class="badge badge-danger">Disabled</span>';
            } ?>
        </div>
    </dd>
    <dt>ionCube Loaders</dt>
    <dd>
        <div>
            <?php
            if (extension_loaded('ionCube Loader')) {
                echo '<span class="badge badge-success">Enabled</span>';
            }
            else {
                echo '<span class="badge badge-warning">Disabled / Run-time Loaded</span>';
            } ?>
        </div>
        <div>
            <small>Important: ionCube Loaders v10 are required.
                For more information on how to install them, please
                <a href="http://www.ioncube.com/loader_installation.php" target="_blank">click here</a>. <br>
                If they are run-time loaded, please disregard this message.
            </small>
        </div>
    </dd>
    <dt>Writable Files / Folders</dt>
    <dd>
        <div>
            <label class="badge badge-info">File: global.config.php</label>
            <?php
            if (is_writable(APPLICATION_PATH . '/config/global.config.php')) {
                echo '<span class="badge badge-success">Writable</span>';
            }
            else {
                $requirementsMet = false;
                echo '<span class="badge badge-danger">Not Writable</span>
                        <p><small>Please give writing permissions to <strong>/config/global.config.php</strong></small></p>';
            } ?>
        </div>
        <div>
            <label class="badge badge-info">File: admin/module.config.php</label>
            <?php
            if (is_writable(APPLICATION_PATH . '/module/Admin/config/module.config.php')) {
                echo '<span class="badge badge-success">Writable</span>';
            }
            else {
                $requirementsMet = false;
                echo '<span class="badge badge-danger">Not Writable</span>
                        <p><small>Please give writing permissions to <strong>/module/Admin/config/module.config.php</strong></small></p>';
            } ?>
        </div>
        <div>
            <label class="badge badge-info">Folder: /cache/</label>
            <?php
            if (is_writable(APPLICATION_PATH . '/cache')) {
                echo '<span class="badge badge-success">Writable</span>';
            }
            else {
                $requirementsMet = false;
                echo '<span class="badge badge-danger">Not Writable</span>';
            } ?>
        </div>
        <div>
            <label class="badge badge-info">Folder: /uploads/</label>
            <?php echo (is_writable(APPLICATION_PATH . '/uploads')) ?
                '<span class="badge badge-success">Writable</span>' : '<span class="badge badge-warning">Not Writable</span>'; ?>
        </div>
        <div>
            <label class="badge badge-info">Folder: /uploads/cache/</label>
            <?php echo (is_writable(APPLICATION_PATH . '/uploads/cache')) ?
                '<span class="badge badge-success">Writable</span>' : '<span class="badge badge-warning">Not Writable</span>'; ?>
        </div>
    </dd>
    <dt>
        cURL Library
    </dt>
    <dd>
        <div>
            <?php echo function_exists('curl_version') ? '<span class="badge badge-success">Enabled</span>' : '<span class="badge badge-warning">Disabled</span>'; ?>
        </div>
        <div>
            <small>(optional) The cURL library is needed by the USPS and Australia Post shipping modules.</small>
        </div>
    </dd>
    <dt>
        allow_url_fopen = on
    </dt>
    <dd>
        <div>
            <?php echo ini_get('allow_url_fopen') ? '<span class="badge badge-success">Enabled</span>' : '<span class="badge badge-warning">Disabled</span>'; ?>
        </div>
        <div>
            <small>(optional) Required if you wish to allow remote images to be added to listings.</small>
        </div>
    </dd>
    <dt>
        SOAPClient
    </dt>
    <dd>
        <div>
            <?php echo class_exists('SOAPClient') ? '<span class="badge badge-success">Enabled</span>' : '<span class="badge badge-warning">Disabled</span>'; ?>
        </div>
        <div>
            <small>(optional) The SOAPClient library is needed by the UPS and FedEx shipping modules.</small>
        </div>
    </dd>
    <dt>Exif Library</dt>
    <dd>
        <div>
            <?php echo function_exists('exif_read_data') ? '<span class="badge badge-success">Enabled</span>' : '<span class="badge badge-warning">Disabled</span>'; ?>
        </div>
        <div>
            <small>(optional) The Exif library is required for rotating certain images uploaded by smartphones or
                tablets.
            </small>
        </div>

    </dd>
</dl>

<?php
if ($requirementsMet === true) {
    $formId = $this->form->getModel()->getFormId();

    if (in_array('upgraded', $formId)) {
        echo '<div class="alert alert-warning">Installation is not possible because you have already tried to install previously. In order to repeat the installation process, '
            . 'please copy <strong>global.config-original.php</strong> over <strong>global.config.php</strong> and refresh this page.</div>';
    }
    else {
        echo $this->form;
    }
}
else {
    echo '<div class="alert alert-danger">Please make sure that all mandatory server requirements are met before proceeding with the installation.</div>';
} ?>

