<?php
/**
 * @version 8.0 [rev.8.0.05]
 */

/** @var bool $inAdmin */
/** @var bool $archived */
/** @var bool $summary */

if (!$summary) {
    $headlineButtons = null;

    if ($inAdmin) {
        $container = $this->navigation()->getInitialContainer()
            ->findOneBy('label', $this->_('Messaging Filter'));

        $headlineButtons .= $this->navigation($container, 'navigation/browse-filter.phtml')->menu();
    }

    $this->setGlobal('headlineButtons', $headlineButtons);
    ?>

    <nav class="navbar p-0 mb-4">
        <form class="form-inline ml-auto"
              action=""
              method="get">

            <?php
            if ($inAdmin) {
                echo $this->formElement('hidden', 'filter', $this->filter)
                    ->render();
            }
            ?>

            <div class="mr-1">
                <?php echo $this->formElement('text', 'keywords', $this->keywords)
                    ->setAttributes(array('placeholder' => $this->_('Keywords'), 'class' => 'form-control input-default'))
                    ->render();
                ?>
            </div>

            <?php echo $this->formElement('submit', 'submit', $this->_('Search'))
                ->setAttributes(array('class' => 'btn btn-secondary'))
                ->render();
            ?>
        </form>
    </nav>
<?php } ?>

<form action="" method="post">
    <?php echo $this->formElement('hidden', 'option', '')->render(); ?>
    <div class="table-responsive">
        <table class="table table-hover">
            <caption>
                <?php echo sprintf(
                    $this->pluralize(
                        $count = $this->paginator->getPages()->totalItemCount,
                        $this->_('<strong>%s</strong> message found.'),
                        $this->_('<strong>%s</strong> messages found.')
                    ), $count); ?>

                <?php if ($this->paginator->getPages()->totalItemCount > 1) { ?>
                    <?php echo sprintf(
                        $this->_('Showing results <strong>%s</strong> to <strong>%s</strong>'),
                        $this->paginator->getPages()->firstItemNumber,
                        $this->paginator->getPages()->lastItemNumber); ?>
                <?php } ?>
            </caption>
            <?php if ($this->paginator->getPages()->totalItemCount) { ?>
                <thead class="thead-light">
                <tr>
                    <?php if (!$archived && !$summary) { ?>
                        <th class="size-tiny">
                            <?php echo $this->formElement('checkbox', 'selectAll')
                                ->setMultiOptions(array(1 => null))
                                ->render();
                            ?>
                        </th>
                    <?php } ?>
                    <th class="size-tiny"></th>
                    <th><?php echo $this->_('Message Title'); ?></th>
                    <?php if (in_array($this->filter, array('received', 'all'))) { ?>
                        <th class="size-medium"><?php echo $this->_('From'); ?></th>
                    <?php } ?>
                    <?php if (in_array($this->filter, array('sent', 'all'))) { ?>
                        <th class="size-medium"><?php echo $this->_('To'); ?></th>
                    <?php } ?>

                </tr>
                </thead>
            <?php } ?>
            <tbody>
            <?php
            /** @var \Ppb\Db\Table\Row\Message $message */
            foreach ($this->paginator as $message) {
                $link = $message->link($inAdmin);
                $topicTitle = $this->message($message)->topicTitle();
                ?>
                <tr>
                    <?php if (!$archived && !$summary) { ?>
                        <td>
                            <?php echo $this->formElement('checkbox', 'id')
                                ->setMultiOptions(array($message['id'] => null))
                                ->setAttributes(array('class' => 'select-all'))
                                ->setMultiple()
                                ->render();
                            ?>
                        </td>
                    <?php } ?>
                    <td>
                        <?php if (!$message['flag_read']) { ?>
                            <span data-feather="mail"></span>
                        <?php } ?>
                    </td>
                    <td>
                        <div>
                            <?php if ($link !== false) { ?>
                                <a href="<?php echo $this->url($link); ?>">
                                    <?php echo $this->fieldDisplay($this->renderText($message['title']), null, $this->_('Message')); ?>
                                </a>
                                <?php
                            }
                            else {
                                ?>
                                <?php echo $this->renderText($message['title']); ?>
                            <?php } ?>
                        </div>
                        <?php if (!empty($topicTitle)) { ?>
                            <div>
                                <strong><?php echo $this->renderText($topicTitle); ?></strong>
                            </div>
                        <?php } ?>

                        <div>
                            <small class="text-muted"><?php echo $this->date($message['created_at']); ?></small>
                        </div>

                        <?php if ($inAdmin) { ?>
                            <div class="mt-2">
                                <small><?php echo $this->renderText($message['content'], true); ?></small>
                            </div>
                        <?php } ?>
                    </td>


                    <?php if (in_array($this->filter, array('received', 'all'))) { ?>
                        <td>
                            <?php echo $this->userDetails($message->findParentRow('\Ppb\Db\Table\Users',
                                'Sender'))->display(); ?>
                        </td>
                    <?php } ?>
                    <?php if (in_array($this->filter, array('sent', 'all'))) {
                        $recipients = $message->getRecipients();
                        ?>
                        <td>
                            <?php
                            /** @var \Ppb\Db\Table\Row\User $recipient */
                            foreach ($recipients as $recipient) { ?>
                                <div><?php echo $this->userDetails($recipient)->display(); ?></div>
                            <?php } ?>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
    <?php if ($this->paginator->getPages()->totalItemCount) { ?>
        <?php if (!$archived && !$summary) { ?>
            <div class="buttons-sticky-bottom">
                <?php if ($inAdmin) { ?>
                    <button class="btn btn-danger confirm-form" value="delete"
                            data-message="<?php echo $this->_('Are you sure you want to delete these messages?'); ?>">
                        <?php echo $this->_('Delete'); ?>
                    </button>
                    <?php
                }
                else {
                    ?>
                    <button class="btn btn-secondary confirm-form" value="archive"
                            data-message="<?php echo $this->_('Are you sure you want to archive these messages?'); ?>">
                        <?php echo $this->_('Archive'); ?>
                    </button>
                <?php } ?>
            </div>
        <?php } ?>
    <?php } ?>
</form>


<?php
if (!$summary) {
    echo $this->pagination($this->paginator, 'sliding', 'partials/pagination.phtml');
}
?>

