<?php
/**
 * @version 8.0 [rev.8.0.01]
 */
?>

<?php if (count($this->breadcrumbs) > 0) { ?>
    <ol class="breadcrumb">
        <?php
        /* @var \Ppb\Navigation\Page\ContentSection $page */
        foreach ($this->breadcrumbs as $page) {
            $class = array('breadcrumb-item');

            if ($page->isActive()) {
                $class[] = 'active';
            }
            ?>
            <li class="<?php echo implode(' ', $class); ?>">
                <?php echo $page->label; ?>
            </li>
        <?php } ?>
    </ol>
<?php } ?>

