<?php
/**
 * @version 8.2 [rev.8.2.01]
 */

/** @var \Ppb\Db\Table\Rowset\Categories $categories */
?>
<nav class="navbar p-0 mb-4">
    <form class="form-inline ml-auto"
          action="<?php echo $this->url(array('action' => 'browse'), null, true, array('page')); ?>"
          method="get">
        <div class="mr-1">
            <?php echo $this->formElement('text', 'keywords')
                ->setAttributes(array('placeholder' => $this->_('Enter Store Name'), 'class' => 'form-control input-medium'))
                ->render();
            ?>
        </div>
        <?php echo $this->formElement('submit', 'submit', $this->_('Search'))
            ->setAttributes(array('class' => 'btn btn-secondary'))
            ->render();
        ?>
    </form>
</nav>

<div class="row mt-3">
    <div class="col-sm-8">
        <!-- FEATURED STORES -->
        <?php
        $filter = array('active', 'featured');
        if ($this->settings['hide_empty_stores']) {
            array_push($filter, 'not-empty');
        }
        $featuredStores = $this->stores('partials/stores-cards.phtml')
            ->setVariables(array('gridClass' => 'col-6 col-sm-4 card-grid'))
            ->fetchStores(array('filter' => $filter, 'sort' => 'rand', 'limit' => 6))
            ->getStores();

        if (count($featuredStores) > 0) {
            ?>

            <div class="mt-3 mb-3 pt-2 pb-1 px-3 bg-light">
                <?php
                echo $this->navigation()->setPartial('navigation/subtitle.phtml')->headline(array(
                    'headline' => $this->_('Featured Stores'),
                ));
                ?>

                <?php echo $this->stores()->render(); ?>
            </div>
        <?php } ?>
        <!-- /FEATURED STORES -->


        <?php if (!$this->settings['disable_store_categories']) { ?>
            <!-- CATEGORIES -->
            <div class="mt-4">
                <?php
                echo $this->navigation()->setPartial('navigation/subtitle.phtml')->headline(array(
                    'headline' => $this->_('Search by Category'),
                ));
                ?>

                <div class="row">
                    <?php foreach ($categories as $category) { ?>
                        <div class="col-sm-6">
                            <a href="<?php echo $this->url(array('action' => 'browse', 'parent_id' => $category['id']), null, true); ?>"><?php echo $this->_($category['name']); ?></a>
                        </div>
                    <?php } ?>
                </div>
            </div>
            <!-- /CATEGORIES -->
        <?php } ?>
    </div>
    <div class="col-sm-4">
        <!-- STANDARD STORES -->
        <?php
        $filter = array('active', 'standard');
        if ($this->settings['hide_empty_stores']) {
            array_push($filter, 'not-empty');
        }
        $standardStores = $this->stores()
            ->fetchStores(array('filter' => $filter, 'sort' => 'rand', 'limit' => 8))
            ->getStores();

        if (count($standardStores) > 0) { ?>
            <div class="standard-stores">
                <?php
                echo $this->navigation()->setPartial('navigation/subtitle.phtml')->headline(array(
                    'headline' => $this->_('Standard Stores'),
                ));
                ?>

                <?php
                /** @var \Ppb\Db\Table\Row\User $store */
                foreach ($standardStores as $store) { ?>
                    <h6 class="mb-1">
                        <a href="<?php echo $this->url($store->storeLink()); ?>"><?php echo $store->storeName(); ?></a>
                    </h6>
                <?php } ?>
            </div>
        <?php } ?>
        <!-- /STANDARD STORES -->

        <div class="mt-4">
            <?php
            echo $this->navigation()->setPartial('navigation/subtitle.phtml')->headline(array(
                'headline' => $this->_('Open a Store'),
            ));
            ?>

            <h6><?php echo $this->_('Would you like to have your own store?'); ?></h6>

            <p><?php echo $this->_('Build your own brand with an online store that\'s easy to start and manage.'); ?></p>

            <div class="text-right">
                <a class="btn btn-default"
                   href="<?php echo $this->url(array('module' => 'members', 'controller' => 'store', 'action' => 'setup')); ?>">
                    <?php echo $this->_('Open a Store'); ?></a>
            </div>
        </div>
    </div>
</div>