<?php
/**
 * @version 8.0 [rev.8.0.01]
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta content="width=device-width; initial-scale=1.0;" name="viewport"/>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="<?php echo $this->sitePath; ?>/css/email.css" rel="stylesheet">
    <link href="<?php echo $this->sitePath; ?>/css/default.css" rel="stylesheet">
    <link href="<?php echo $this->sitePath; ?>/css/mods.css" rel="stylesheet">

    <style type="text/css">
        .site-logo {
            max-width: 200px;
        }
    </style>

</head>


<body class="bg-light"
      style="outline: 0; width: 100%; min-width: 100%; height: 100%; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; font-family: Helvetica, Arial, sans-serif; line-height: 24px; font-weight: normal; font-size: 14px; -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box; margin: 0; padding: 0; border: 0;">
<div class="preview" style="display: none; max-height: 0px; overflow: hidden;">
    <?php //echo $this->_($this->headerMessage); ?>
</div>
<table valign="top" class="bg-light body"
       style="outline: 0; width: 100%; min-width: 100%; height: 100%; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; font-family: Helvetica, Arial, sans-serif; line-height: 24px; font-weight: normal; font-size: 14px; -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; border-collapse: collapse; margin: 0; padding: 0; border: 0;"
       bgcolor="#f8f9fa">
    <tbody>
    <tr>
        <td valign="top"
            style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 14px; margin: 0;"
            align="left" bgcolor="#f8f9fa">


            <table class="container" border="0" cellpadding="0" cellspacing="0"
                   style="font-family: Helvetica, Arial, sans-serif; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; border-collapse: collapse; width: 100%;">
                <tbody>
                <tr>
                    <td align="center"
                        style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 14px; margin: 0; padding: 0 16px;">
                        <!--[if (gte mso 9)|(IE)]>
                        <table align="center">
                            <tbody>
                            <tr>
                                <td width="600">
                        <![endif]-->
                        <table align="center" border="0" cellpadding="0" cellspacing="0"
                               style="font-family: Helvetica, Arial, sans-serif; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; border-collapse: collapse; width: 100%; max-width: 600px; margin: 0 auto;">
                            <tbody>
                            <tr>
                                <td style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 14px; margin: 0;"
                                    align="left">

                                    <table class="mx-auto" align="center" border="0" cellpadding="0" cellspacing="0"
                                           style="font-family: Helvetica, Arial, sans-serif; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; border-collapse: collapse; margin: 0 auto;">
                                        <tbody>
                                        <tr>
                                            <td style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 14px; margin: 0;"
                                                align="left">
                                                <table class="s-4 w-100" border="0" cellpadding="0" cellspacing="0"
                                                       style="width: 100%;">
                                                    <tbody>
                                                    <tr>
                                                        <td height="24"
                                                            style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 24px; width: 100%; height: 24px; margin: 0;"
                                                            align="left">

                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>

                                                <a href="<?php echo $this->sitePath; ?>">
                                                    <img class="site-logo"
                                                         src="<?php echo $this->sitePath; ?>/<?php echo $this->siteLogo; ?>"
                                                         style="height: auto; line-height: 100%; outline: none; text-decoration: none; border: 0 none;">
                                                </a>

                                                <table class="s-3 w-100" border="0" cellpadding="0" cellspacing="0"
                                                       style="width: 100%;">
                                                    <tbody>
                                                    <tr>
                                                        <td height="16"
                                                            style="border-spacing: 0px; border-collapse: collapse; line-height: 16px; font-size: 14px; width: 100%; height: 16px; margin: 0;"
                                                            align="left">

                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>


                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>


                                    <table border="0" cellpadding="0" cellspacing="0"
                                           style="font-family: Helvetica, Arial, sans-serif; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; border-collapse: separate !important; border-radius: 4px; width: 100%; overflow: hidden; border: 1px solid #dee2e6;"
                                           bgcolor="#ffffff">
                                        <tbody>
                                        <tr>
                                            <td style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 14px; width: 100%; margin: 0;"
                                                align="left">
                                                <div style="border-top-width: 5px; border-top-color: #dee2e6; border-top-style: solid;">
                                                    <table class="card-body" border="0" cellpadding="0" cellspacing="0"
                                                           style="font-family: Helvetica, Arial, sans-serif; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; border-collapse: collapse; width: 100%;">
                                                        <tbody>
                                                        <tr>
                                                            <td style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 14px; width: 100%; margin: 0; padding: 20px;"
                                                                align="left">
                                                                <div>
                                                                    <h4 class="text-center"
                                                                        style="margin-top: 0; margin-bottom: 0; font-weight: 500; color: inherit; vertical-align: baseline; font-size: 24px; line-height: 28.8px;"
                                                                        align="center">
                                                                        <strong><?php echo $this->_($this->headerMessage); ?></strong>
                                                                    </h4>
                                                                    <div class="hr "
                                                                         style="width: 100%; margin: 20px 0; border: 0;">
                                                                        <table border="0" cellpadding="0"
                                                                               cellspacing="0"
                                                                               style="font-family: Helvetica, Arial, sans-serif; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; border-collapse: collapse; width: 100%;">
                                                                            <tbody>
                                                                            <tr>
                                                                                <td style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 14px; border-top-width: 1px; border-top-color: #dddddd; border-top-style: solid; height: 1px; width: 100%; margin: 0;"
                                                                                    align="left"></td>
                                                                            </tr>
                                                                            </tbody>
                                                                        </table>
                                                                    </div>

                                                                    <?php echo $this->getContent(); ?>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                    </table>

                                                </div>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <table class="s-4 w-100" border="0" cellpadding="0" cellspacing="0"
                                           style="width: 100%;">
                                        <tbody>
                                        <tr>
                                            <td height="24"
                                                style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 24px; width: 100%; height: 24px; margin: 0;"
                                                align="left">

                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>


                                    <div class="text-center text-muted " style="color: #636c72; font-size: 12px;"
                                         align="center">
                                        &copy;<?php echo date('Y'); ?>
                                        <a href="<?php echo $this->sitePath; ?>"><?php echo $this->siteName; ?></a>.
                                        <?php echo $this->_('All rights reserved.'); ?>
                                    </div>

                                    <table class="s-4 w-100" border="0" cellpadding="0" cellspacing="0"
                                           style="width: 100%;">
                                        <tbody>
                                        <tr>
                                            <td height="24"
                                                style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 24px; width: 100%; height: 24px; margin: 0;"
                                                align="left">

                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>


                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <!--[if (gte mso 9)|(IE)]>
                        </td>
                        </tr>
                        </tbody>
                        </table>
                        <![endif]-->
                    </td>
                </tr>
                </tbody>
            </table>


        </td>
    </tr>
    </tbody>
</table>

</body>

</html>