<?php
/**
 * @version 8.0 [rev.8.0.01]
 */
/** @var bool $all */
/** @var bool $dropdown */
/** @var string $filter */
/** @var \Ppb\Db\Table\Row\Listing $listing */

$dropdown = (isset($dropdown)) ? $dropdown : false;
$filter = (isset($filter)) ? $filter : null;
$all = (isset($all)) ? $all : false;

$buttons = array();

if ($listing->canEdit()) {
    $buttons[] = array(
        'title'   => $this->_('Edit Listing'),
        'label'   => $this->_('Edit'),
        'class'   => 'btn btn-secondary mb-1',
        'href'    => $this->url(array('id' => $listing['id']), 'listings-edit'),
        'feather' => 'folder',
    );
}

if ($all && !$listing['active']) {
    $buttons[] = array(
        'title'   => $this->_('Pay Listing Setup Fee'),
        'label'   => $this->_('Pay Listing Setup Fee'),
        'class'   => 'btn btn-success mb-1',
        'href'    => $this->url(array('module' => 'app', 'controller' => 'payment', 'action' => 'listing-setup', 'id' => $listing['id'])),
        'feather' => 'airplay',
    );
}

if ($filter != 'drafts') {
    $buttons[] = array(
        'title'   => $this->_('List Similar'),
        'label'   => $this->_('List Similar'),
        'class'   => 'btn btn-light mb-1',
        'href'    => $this->url(array('id' => $listing['id']), 'listings-create-similar'),
        'feather' => 'airplay',
    );
}
else {
    $buttons[] = array(
        'title'   => $this->_('List Draft'),
        'label'   => $this->_('List Draft'),
        'class'   => 'btn btn-success mb-1',
        'href'    => $this->url(array('id' => $listing['id']), 'listings-list-draft'),
        'feather' => 'file-text',
    );
}

if ($all && $listing->canClose()) {
    $buttons[] = array(
        'title'        => $this->_('Close Listing'),
        'label'        => $this->_('Close'),
        'class'        => 'btn btn-warning mb-1',
        'href'         => $this->url(array('module' => 'listings', 'controller' => 'listing', 'action' => 'close', 'id' => $listing['id'])),
        'data-message' => $this->_('Are you sure you want to close this listing?'),
        'feather'      => 'slash',
    );
}

if ($listing->canDelete()) {
    $buttons[] = array(
        'title'        => $this->_('Delete Listing'),
        'label'        => $this->_('Delete'),
        'class'        => 'btn btn-danger mb-1',
        'href'         => $this->url(array('module' => 'listings', 'controller' => 'listing', 'action' => 'delete', 'id' => $listing['id']),
            null, true),
        'data-message' => $this->_('Are you sure you want to delete this listing?'),
        'feather'      => 'x',
    );
}
?>

<?php foreach ($buttons as $button) {
    $attributes = array();
    foreach ($button as $key => $value) {
        if ($key == 'class' && $dropdown) {
            $value = 'dropdown-item';
        }

        if ($key == 'class' && !empty($button['data-message'])) {
            $value .= ' ' . 'confirm-box';
        }

        if (!in_array($key, array('label', 'feather'))) {
            $attributes[] = $key . '="' . $value . '"';
        }
    }

    echo '<a ' . implode(' ', $attributes) . '>'
        . ((!empty($button['feather']) && !$dropdown) ? '<span data-feather="' . $button['feather'] . '"></span> ' : '')
        . ((!empty($button['label'])) ? $button['label'] : '')
        . '</a> ';
} ?>

