<p>
    <?php echo $this->_('A new sale balance withdrawal request has been made.'); ?>
</p>
<div>
    <?php echo $this->_('Request details:'); ?>
</div>
<ul>
    <li>
        <?php echo $this->_('Username:'); ?>
        <b><?php echo $this->data['username']; ?></b>
    </li>
    <li>
        <?php echo $this->_('Amount:'); ?>
        <b><?php echo $this->amount($this->data['withdrawal']['amount'], $this->data['withdrawal']['currency']); ?></b>
    </li>
</ul>
<div>
    <?php echo $this->_('Please'); ?>
    [ <a
        href="<?php echo $this->sitePath . $this->url(array('module' => 'admin', 'controller' => 'tools', 'action' => 'balance-withdrawals'), null, false, null, false); ?>">
        <?php echo $this->_('click here'); ?>
    </a> ]
    <?php echo $this->_('to access the balance withdrawals page. Please note that you will have to log in first.'); ?>
</div>

