<?php
/**
 * @version 8.0 [rev.8.0.03]
 */
?>

<?php if ($this->canPurchase !== true) { ?>
    <div class="alert alert-secondary">
        <?php echo $this->canPurchase; ?>
    </div>

    <?php if (empty($this->loggedInUser['id'])) {
        $redirectUrl = $this->request()->getRequest()->getBaseUrl() .
            $this->request()->getRequest()->getRequestUri();
        ?>
        <div class="mt-3">
            <?php echo $this->action('login', 'user', 'members', array('redirect' => $redirectUrl, 'no_redirect_parent' => 1, 'async' => 1)); ?>
        </div>
    <?php } ?>
<?php }
else if ($this->cartBox) { ?>
    <?php
    echo $this->actionMessages()->setMessages($this->messages)->render();
    $this->messages = null;
    ?>

    <div class="cart-dropdown">
        <?php echo $this->cartBox; ?>
    </div>
<?php }
else {
    if ($this->form->isRedirectParent()) {
        echo json_encode(array(
            'redirectUrl' => $this->form->getRedirectUrl()
        ));
    }
    else {
        echo $this->form;
    }
} ?>

