<?php
/**
 * @version 8.2 [rev.8.2.01]
 */
/**
 * MOD:- DISCOUNT RULES
 *
 * @version 3.0
 * MOD:- CURRENCY SELECTOR
 */

/* @var \Ppb\Db\Table\Row\Listing $listing */

$class = (isset($class)) ? $class : array();
$id = (isset($id)) ? $id : null;

if (!isset($currentBid)) {
    $currentBid = ($listing->isAuction()) ? $listing->currentBid(true) : $listing['buyout_price'];
}

$class[] = 'current-price-' . $listing['id'];

if ($currentBid > 0) {
    if ($listing->isClassified()) {
        $class[] = 'text-classified';
    }
    else if ($listing->isProduct()) {
        ## -- ADD 1L -- [ MOD:- CURRENCY SELECTOR ]
        $this->amount(false)->setConvert(true);
        $class[] = 'text-buyout';
    }
    else if ($currentBid < $listing['reserve_price']) {
        $class[] = 'text-under-reserve';
    }
    else if ($currentBid >= $listing['reserve_price']) {
        $class[] = 'text-over-reserve';
    } ?>

    <?php
    ## -- START :: ADD -- [ MOD:- DISCOUNT RULES @version 1.0 ]
    $discountedPrice = $listing->discountedPrice();
    if ($discountedPrice > 0 && $discountedPrice < $currentBid) {
        ?>

        <span class="original-price" <?php echo ($id) ? 'id="original-price"' : ''; ?>>
            <?php echo $this->amount($currentBid, $listing['currency']); ?>
        </span>
        <?php
        $currentBid = $discountedPrice;
    }
    ## -- END :: ADD -- [ MOD:- DISCOUNT RULES @version 1.0 ]
    ?>

    <span class="<?php echo implode(' ', $class); ?>" <?php echo ($id) ? 'id="' . $id . '"' : ''; ?>>
        <?php echo $this->amount($currentBid, $listing['currency']); ?>
    </span>
<?php 
    ## -- ADD 1L -- [ MOD:- CURRENCY SELECTOR ]
    $this->amount(false)->setConvert(false);
} ?>
