<?php
/**
 * MOD:- DISCOUNT RULES
 *
 * @version 2.0
 */

$headlineButtons = null;

$headlineButtons .= '<a class="btn btn-outline-secondary" '
    . 'href="' . $this->url(array('action' => 'add-discount-rule')) . '">'
    . $this->_('Create Discount Rule') . '</a>';

$this->setGlobal('headlineButtons', $headlineButtons);
?>

<div class="table-responsive">
    <table class="table table-hover">
        <caption>
            <?php echo sprintf(
                $this->pluralize(
                    $count = $this->paginator->getPages()->totalItemCount,
                    $this->_('<strong>%s</strong> discount rule found.'),
                    $this->_('<strong>%s</strong> discount rules found.')
                ), $count); ?>

            <?php if ($this->paginator->getPages()->totalItemCount > 1) { ?>
                <?php echo sprintf(
                    $this->_('Showing results <strong>%s</strong> to <strong>%s</strong>'),
                    $this->paginator->getPages()->firstItemNumber,
                    $this->paginator->getPages()->lastItemNumber); ?>
            <?php } ?>
        </caption>
        <?php if ($this->paginator->getPages()->totalItemCount) { ?>
            <thead class="thead-light">
            <tr>
                <th class="size-medium"><?php echo $this->_('Name'); ?></th>
                <th><?php echo $this->_('Details'); ?></th>
                <th class="size-actions"><?php echo $this->_('Actions'); ?></th>
            </tr>
            </thead>
        <?php } ?>
        <tbody>
        <?php
        /** @var \Ppb\Db\Table\Row\DiscountRule $discountRule */
        foreach ($this->paginator as $discountRule) {
            ?>
            <tr>
                <td>
                    <?php echo $discountRule['name']; ?>
                    <div class="mt-2">
                        <?php echo $this->fieldDisplay($discountRule['active'],
                            '<span class="badge badge-success">' . $this->_('Active') . '</span>',
                            '<span class="badge badge-danger">' . $this->_('Inactive') . '</span>'); ?>
                    </div>
                </td>
                <td>

                    <dl class="dl-variable">
                        <dt>
                            <span><?php echo $this->_('Reduction'); ?></span>
                        </dt>
                        <dd><?php echo ($discountRule['reduction_type'] == 'percent') ?
                                $discountRule['reduction_amount'] . '%' : $this->amount($discountRule['reduction_amount']); ?>
                        </dd>

                        <?php if ($discountRule['start_date']) { ?>
                            <dt>
                                <span><?php echo $this->_('Start Date'); ?></span>
                            </dt>
                            <dd><?php echo $this->date($discountRule['start_date']); ?></dd>
                        <?php } ?>

                        <?php if ($discountRule['expiration_date']) { ?>
                            <dt>
                                <span><?php echo $this->_('Expiration Date'); ?></span>
                            </dt>
                            <dd><?php echo $this->date($discountRule['expiration_date']); ?></dd>
                        <?php } ?>

                        <dt>
                            <span><?php echo $this->_('Priority'); ?></span>
                        </dt>
                        <dd><?php echo intval($discountRule['priority']); ?></dd>

                        <dt>
                            <span><?php echo $this->_('Stop Further Rules'); ?></span>
                        </dt>
                        <dd><?php echo $this->fieldDisplay($discountRule['stop_further_rules'], $this->_('Yes'), $this->_('No')); ?></dd>

                        <?php if ($discountRule['conditions'] != null) { ?>
                            <dt>
                                <span><?php echo $this->_('Conditions'); ?></span>
                            </dt>
                            <dd><code><?php echo $discountRule['conditions']; ?></code></dd>
                        <?php } ?>
                    </dl>

                </td>
                <td>
                    <a class="btn btn-secondary mb-1"
                       href="<?php echo $this->url(array('action' => 'edit-discount-rule', 'id' => $discountRule['id']), null, true); ?>"
                       title="<?php echo $this->_('Edit Discount Rule'); ?>">
                        <span data-feather="folder"></span>
                        <?php echo $this->_('Edit'); ?>
                    </a>
                    <a class="btn btn-danger mb-1 confirm-box"
                       href="<?php echo $this->url(array('action' => 'delete-discount-rule', 'id' => $discountRule['id']),
                           null, true); ?>"
                       title="<?php echo $this->_('Delete Discount Rule'); ?>"
                       data-message="<?php echo $this->_('Are you sure you want to delete this discount rule?'); ?>">
                        <span data-feather="x"></span>
                        <?php echo $this->_('Delete'); ?>
                    </a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<?php echo $this->pagination($this->paginator, 'sliding', 'partials/pagination.phtml'); ?>

