<?php
/**
 * MOD:- EBAY IMPORTER
 *
 * @version 1.2
 */
?>
<?php if ($this->form->isPosted()) { ?>
    <div class="card mb-4">
        <div class="card-body">
            <p id="ebay-parser-info" class="text-info">
                <?php echo $this->_('Please wait, upload in progress...'); ?>
            </p>
            <p>
                <small>
                    <?php echo $this->_('Depending on the number of items you are uploading, the process may take several minutes to complete. <br>'
                        . 'Please do not close or refresh this window until complete.'); ?>
                </small>
            </p>
            <div class="progress">
                <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar"
                     aria-valuenow="0"
                     aria-valuemin="0"
                     aria-valuemax="100" style="width: 1%">
                </div>
            </div>
            <p id="ebay-parser-progress"></p>
            <p id="parser-messages"></p>
        </div>
    </div>
<?php }
else {
    ?>
    <div class="card mb-4">
        <div class="card-body">
            <div class="mb-3">
                <?php echo $this->_('Using this form you can import your ebay listings using your ebay username.'); ?>
            </div>
            <a class="btn btn-outline-secondary pull-right confirm-box"
               href="<?php echo $this->url(array('action' => 'ebay-remove-items')); ?>"
               data-message="<?php echo $this->_('Warning: This action will remove all ebay listings you have currently imported! Proceed?'); ?>">
                <?php echo $this->_('Remove Imported Ebay Items'); ?></a>
        </div>
    </div>
<?php } ?>

<form action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
    <?php echo $this->form->hiddenElements; ?>

    <?php
    /* @var \Cube\Form\Element $element */
    foreach ($this->form->getElements() as $element) { ?>
        <?php if (!$element->isHidden()) {
            $partial = ($partial = $element->getPartial()) ? $partial : 'partials/form-element.phtml';
            ?>
            <?php echo $this->partial($partial, array('element' => $element)); ?>
        <?php } ?>
    <?php } ?>
</form>