<?php
/**
 * @version 8.0 [rev.8.0.02]
 */
?>

<nav class="navbar p-0 mb-4">
    <form class="form-inline" action="" method="post">
        <div class="mr-1">
            <?php echo $this->formElement('select', 'email', $this->email)
                ->setMultiOptions(\Ppb\Utility::getSystemEmails())
                ->setAttributes(array(
                    'class' => 'form-control input-large'))
                ->render();
            ?>
        </div>
        <?php echo $this->formElement('submit', 'submit', $this->_('Proceed'))
            ->setAttributes(array('class' => 'btn btn-secondary'))
            ->render();
        ?>
    </form>
</nav>

<?php if ($this->email) { ?>
    <form action="" method="post">
        <input type="hidden" name="email" value="<?php echo $this->email; ?>">

        <div class="form-group">
            <?php echo $this->formElement('textarea', 'text')
                ->setAttributes(array(
                    'rows'  => '24',
                    'class' => 'form-control textarea-code',
                ))
                ->setValue($this->text)
                ->render(); ?>
            <small class="form-text text-muted">
                <?php echo $this->_('<strong>Recommended</strong>: Edit this file with a dedicated php editor. <br>'
                    . '<strong>Important</strong>: entering invalid php code might render your site unusable.'); ?>
            </small>
        </div>

        <div class="form-group">
            <?php echo $this->formElement('submit', 'save', $this->_('Save'))
                ->setAttributes(array('class' => 'btn btn-lg btn-primary'))
                ->render();
            ?>
        </div>
    </form>
<?php } ?>

