<?php
/**
 * @version 8.2 [rev.8.2.01]
 */

$headlineButtons = null;

$headlineButtons .= '<a class="btn btn-outline-secondary" '
    . 'href="' . $this->url(array('action' => 'new-entry')) . '">'
    . $this->_('New Entry') . '</a>';

$this->setGlobal('headlineButtons', $headlineButtons);
?>
<nav class="navbar p-0 mb-4">
    <form class="form-inline ml-auto"
          action="<?php echo $this->url(null, null, true, array('title', 'handle', 'page', 'submit')); ?>" method="get">

        <div class="mr-1">
            <?php echo $this->formElement('text', 'title', $this->title)
                ->setAttributes(array('placeholder' => $this->_('Title'), 'class' => 'form-control input-medium'))
                ->render();
            ?>
        </div>
        <div class="mr-1">
            <?php echo $this->formElement('text', 'handle', $this->handle)
                ->setAttributes(array('placeholder' => $this->_('Section Handle'), 'class' => 'form-control input-medium'))
                ->render();
            ?>
        </div>
        <?php echo $this->formElement('submit', 'submit', 'Search')
            ->setAttributes(array('class' => 'btn btn-secondary'))
            ->render();
        ?>
    </form>
</nav>

<div class="table-responsive">
    <table class="table table-hover">
        <caption>
            <?php echo sprintf(
                $this->pluralize(
                    $count = $this->paginator->getPages()->totalItemCount,
                    $this->_('<strong>%s</strong> entry found.'),
                    $this->_('<strong>%s</strong> entries found.')
                ), $count); ?>

            <?php if ($this->paginator->getPages()->totalItemCount > 1) { ?>
                <?php echo sprintf(
                    $this->_('Showing results <strong>%s</strong> to <strong>%s</strong>'),
                    $this->paginator->getPages()->firstItemNumber,
                    $this->paginator->getPages()->lastItemNumber); ?>
            <?php } ?>
        </caption>
        <?php if ($this->paginator->getPages()->totalItemCount) { ?>
            <thead class="thead-light">
            <tr>
                <th><?php echo $this->_('Title'); ?></th>
                <th class="size-small"><?php echo $this->_('Status'); ?></th>
                <th class="size-mini"><?php echo $this->_('Locale'); ?></th>
                <th class="size-medium"><?php echo $this->_('Section Handle'); ?></th>
                <th class="size-large"><?php echo $this->_('URI'); ?></th>
                <th class="size-medium"><?php echo $this->_('Actions'); ?></th>
            </tr>
            </thead>
        <?php } ?>
        <tbody>
        <?php
        /** @var \Ppb\Db\Table\Row\ContentEntry $entry */
        foreach ($this->paginator as $entry) {
            $section = $entry->findParentRow('\Ppb\Db\Table\ContentSections');
            $sectionHandle = ($section instanceof \Ppb\Db\Table\Row\ContentSection) ? $section['handle'] : null;
            $entryLink = $entry->link(true);
            ?>
            <tr>
                <td>
                    <div><?php echo $this->fieldDisplay($entry['title']); ?></div>
                    <div class="mt-4">
                        <a class="btn btn-success mb-1" target="_blank"
                           href="<?php echo $this->url($entryLink, null, false, null, true, false); ?>"
                           title="<?php echo $this->_('Preview Entry'); ?>">
                            <span data-feather="image"></span>
                            <?php echo $this->_('Preview'); ?>

                        </a>
                    </div>
                </td>
                <td>
                    <?php echo $this->sectionEntryStatus($section, $entry); ?>
                </td>
                <td>
                    <?php if (!empty($entry['locale'])) { ?>
                        <span class="flag-icon flag-icon-<?php echo $this->language()->flagClass($entry['locale']); ?>" title="<?php echo $entry['locale']; ?>"></span>
                    <?php }
                    else { ?>
                        <span class="badge badge-primary"><?php echo $this->_('All'); ?></span>
                    <?php } ?>
                </td>
                <td>
                    <em><?php echo ($sectionHandle != null) ? '<a href="' . $this->url(array('action' => 'sections', 'name' => $sectionHandle)) . '">' . $sectionHandle . '</a>' : $this->_('n/a'); ?></em>
                </td>
                <td>
                    <?php echo ltrim($this->url($entryLink, null, false, null, false), '/'); ?>
                </td>
                <td>
                    <a class="btn btn-secondary mb-1"
                       href="<?php echo $this->url(array('action' => 'edit-entry', 'id' => $entry['id'])); ?>"
                       title="<?php echo $this->_('Edit Entry'); ?>">
                        <span data-feather="folder"></span>
                        <?php echo $this->_('Edit'); ?>
                    </a>
                    <a class="btn btn-danger mb-1 confirm-box"
                       href="<?php echo $this->url(array('action' => 'delete-entry', 'id' => $entry['id']),
                           null, true); ?>"
                       title="<?php echo $this->_('Delete Entry'); ?>"
                       data-message="<?php echo $this->_('Are you sure you want to delete this entry?'); ?>">
                        <span data-feather="x"></span>
                        <?php echo $this->_('Delete'); ?>
                    </a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<?php echo $this->pagination($this->paginator, 'sliding', 'partials/pagination.phtml'); ?>

