<?php
/**
 * @version 8.0 [rev.8.0.01]
 */

$headlineButtons = null;

$headlineButtons .= '<a class="btn btn-outline-secondary" '
    . 'href="' . $this->url(array('action' => 'new-menu')) . '">'
    . $this->_('New Menu') . '</a>';

$this->setGlobal('headlineButtons', $headlineButtons);
?>
<nav class="navbar p-0 mb-4">
    <form class="form-inline ml-auto"
          action="<?php echo $this->url(null, null, true, array('id', 'name', 'page', 'submit')); ?>"
          method="get">

        <div class="mr-1">
            <?php echo $this->formElement('text', 'name', $this->name)
                ->setAttributes(array('placeholder' => $this->_('Name / Handle'), 'class' => 'form-control input-medium'))
                ->render();
            ?>
        </div>
        <?php echo $this->formElement('submit', 'submit', 'Search')
            ->setAttributes(array('class' => 'btn btn-secondary'))
            ->render();
        ?>
    </form>
</nav>

<div class="table-responsive">
    <table class="table table-hover">
        <caption>
            <?php echo sprintf(
                $this->pluralize(
                    $count = $this->paginator->getPages()->totalItemCount,
                    $this->_('<strong>%s</strong> menu found.'),
                    $this->_('<strong>%s</strong> menus found.')
                ), $count); ?>

            <?php if ($this->paginator->getPages()->totalItemCount > 1) { ?>
                <?php echo sprintf(
                    $this->_('Showing results <strong>%s</strong> to <strong>%s</strong>'),
                    $this->paginator->getPages()->firstItemNumber,
                    $this->paginator->getPages()->lastItemNumber); ?>
            <?php } ?>
        </caption>
        <?php if ($this->paginator->getPages()->totalItemCount) { ?>
            <thead class="thead-light">
            <tr>
                <th><?php echo $this->_('Name'); ?></th>
                <th class="size-medium"><?php echo $this->_('Handle'); ?></th>
                <th class="size-medium"><?php echo $this->_('Actions'); ?></th>
            </tr>
            </thead>
        <?php } ?>
        <tbody>
        <?php
        /** @var \Ppb\Db\Table\Row\ContentMenu $menu */
        foreach ($this->paginator as $menu) {
            ?>
            <tr>
                <td>
                    <?php echo $menu['name']; ?>
                </td>
                <td>
                    <em><?php echo $menu['handle']; ?></em>
                </td>
                <td>
                    <a class="btn btn-secondary mb-1"
                       href="<?php echo $this->url(array('action' => 'edit-menu', 'id' => $menu['id'])); ?>"
                       title="<?php echo $this->_('Edit Menu'); ?>">
                        <span data-feather="folder"></span>
                        <?php echo $this->_('Edit'); ?>
                    </a>
                    <a class="btn btn-danger mb-1 confirm-box"
                       href="<?php echo $this->url(array('action' => 'delete-menu', 'id' => $menu['id']),
                           null, true); ?>"
                       title="<?php echo $this->_('Delete Menu'); ?>"
                       data-message="<?php echo $this->_('Are you sure you want to delete this menu?'); ?>">
                        <span data-feather="x"></span>
                        <?php echo $this->_('Delete'); ?>
                    </a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<?php echo $this->pagination($this->paginator, 'sliding', 'partials/pagination.phtml'); ?>

