<?php
/**
 * @version 8.0 [rev.8.0.01]
 */
/** @var \Ppb\Db\Table\Row\User $user */
$user = $this->data['user'];
?>

<p>
    <?php echo $this->_('A new selling privileges request has been made.'); ?>
</p>

<dl class="dl-lg dl-indented">
    <dt>
        <?php echo $this->_('Username:'); ?>
    </dt>
    <dd>
        <?php echo $this->userDetails($user)->display(); ?>
    </dd>
    <dt>
        <?php echo $this->_('Full Name'); ?>
    </dt>
    <dd>
        <?php echo $this->userDetails()->displayFullName(); ?>
    </dd>
    <dt>
        <?php echo $this->_('Address:'); ?>
    </dt>
    <dd>
        <?php echo $this->fieldDisplay($this->userDetails()->displayAddress(', ')); ?>
    </dd>
    <dt>
        <?php echo $this->_('Email:'); ?>
    </dt>
    <dd>
        <?php echo $this->fieldDisplay($user['email']); ?>
    </dd>
    <dt>
        <?php echo $this->_('Phone:'); ?>
    </dt>
    <dd>
        <?php echo $this->fieldDisplay($user['phone']); ?>
    </dd>
</dl>

<p>
    [ <a href="<?php echo $this->sitePath . $this->url(array(
            'module'     => 'admin',
            'controller' => 'users',
            'action'     => 'browse',
            'view'       => 'site',
            'filter'     => 'requested_selling_privileges'), null, false, null, false); ?>">
        <?php echo $this->_('Click here'); ?>
    </a> ]
    <?php echo $this->_('to view a list of accounts with pending selling privileges requests. Please note that you will have to sign in first.'); ?>
</p>
