<?php
/**
 * @version 8.2 [rev.8.2.01]
 */
$logo = $this->form->getGatewayLogo();
$name = $this->form->getGatewayName();
?>

<div class="media mb-3 payment-box">
    <?php if ($logo !== null) { ?>
        <img src="<?php echo $this->baseUrl . $logo; ?>" alt="<?php echo $name; ?>"
             class="d-none d-md-block payment-logo">
    <?php } ?>

    <div class="media-body">
        <div class="d-md-flex justify-content-between">
            <div class="mx-md-3 pb-3 pb-md-0">
                <?php echo $this->form->getGatewayDescription(); ?>
            </div>
            <div>
                <a href="<?php echo $this->form->getAction(); ?>"
                   class="btn btn-lg btn-success"><?php echo $this->_('Make Payment'); ?></a>
            </div>
        </div>
    </div>
</div>


