<?php
/**
 * @version 8.0 [rev.8.0.01]
 */
/* @var int $id
 * @var array                  $multiOptions
 * @var \Ppb\Db\Table\Row\Sale $sale
 */

$quantities = array();
$listingIds = array();

if (count($multiOptions) > 1) {
    $headlineButtons = '<form action="" method="get">'
        . $this->formElement('select', 'id', $id)
            ->setAttributes(array(
                'class'    => 'form-control custom-select input-medium',
                'onchange' => 'this.form.submit();'
            ))
            ->setMultiOptions($multiOptions)
            ->render()
        . '</form>';

    $this->setGlobal('headlineButtons', $headlineButtons);
} ?>

<?php if ($id) {
    echo $this->form;
}
else {
    ?>
    <p class="text-center">
        <?php echo $this->_('The shopping cart is empty.'); ?>
    </p>
<?php } ?>

