<?php
/**
 * @version 8.2 [rev.8.2.01]
 */
?>
<hr>
<div style="text-align: center; font-size: 12px;">
    <?php echo $this->_('To manage your email notifications preferences,'); ?>
    <a href="<?php echo $this->sitePath . $this->url(array('module' => 'members', 'controller' => 'tools', 'action' => 'email-notifications'), null, false, null, false, false); ?>">
        <?php echo $this->_('click here'); ?>.
    </a>
</div>