<?php
/**
 * @version 8.0 [rev.8.0.01]
 */
?>

<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>">
    <?php echo $this->form->hiddenElements; ?>
    <div class="table-responsive">
        <table class="table">
            <caption>
                <?php echo function_exists('curl_version') ?
                    '<span class="badge badge-success">' . $this->_('cURL Enabled') . '</span>' :
                    '<span class="badge badge-warning">' . $this->_('cURL Disabled') . '</span>'; ?>
                <?php echo ini_get('allow_url_fopen') ?
                    '<span class="badge badge-success">' . $this->_('allow_url_fopen Enabled') . '</span>' :
                    '<span class="badge badge-warning">' . $this->_('allow_url_fopen Disabled') . '</span>'; ?>
                <?php echo class_exists('SOAPClient') ?
                    '<span class="badge badge-success">' . $this->_('SOAPClient Enabled') . '</span>' :
                    '<span class="badge badge-warning">' . $this->_('SOAPClient Disabled') . '</span>'; ?>
            </caption>
            <thead class="thead-light">
            <tr>
                <th class="size-small"><?php echo $this->_('Shipping Carrier'); ?></th>
                <th>Settings</th>
                <th class="size-mini"><?php echo $this->_('Enabled'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            $checkboxCounter = 0;
            foreach ((array)$this->form->getData() as $data) { ?>
                <tr>
                    <td>
                        <img src="<?php echo $this->baseUrl . $data['logo_path']; ?>"
                             alt="<?php echo $data['name']; ?>">
                    </td>
                    <td>
                        <?php
                        /* @var \Cube\Form\Element $element */
                        foreach ($this->formElements as $element) {
                            if ($element['form_id'] == $data['name']) {
                                $element = $this->form->getElement($element['id']);
                                $label = $element->getLabel();
                                $description = $element->getDescription();
                                $elementName = $element->getName();

                                if (isset($data[$elementName])) {
                                    $element->setData($data[$elementName]);
                                }

                                $element->setBrackets('[' . $data['id'] . ']')->setMultiple();

                                echo $this->partial('partials/form-element.phtml', array('element' => $element));
                            }
                        }

                        echo (isset($this->carrierDescription[$data['name']])) ? '<div>' . $this->carrierDescription[$data['name']] . '</div>' : ''; ?>
                    </td>
                    <td>
                        <?php echo $this->form->getElement('enabled')
                            ->setData($data['enabled'])
                            ->setBrackets('[' . $checkboxCounter . ']')
                            ->render(); ?>
                        <?php echo $this->form->getElement('id')->setData($data['id'])->render(); ?>
                    </td>
                </tr>
                <?php $checkboxCounter++; ?>
            <?php } ?>
            <tr>
                <td colspan="4"><?php echo $this->form->getElement('submit')->render(); ?></td>
            </tr>
            </tbody>
        </table>
    </div>
</form>