<?php
/**
 * @version 8.0 [rev.8.0.04]
 */

/** @var bool $inAdmin */

$headlineButtons = null;

$headlineButtons .= '<a class="btn btn-outline-secondary" '
    . 'href="' . $this->url(array('action' => 'add-blocked-user')) . '">'
    . $this->_('Add Blocked User') . '</a>';

$this->setGlobal('headlineButtons', $headlineButtons);
?>

<div class="table-responsive">
    <table class="table table-hover">
        <caption>
            <?php echo sprintf(
                $this->pluralize(
                    $count = $this->paginator->getPages()->totalItemCount,
                    $this->_('<strong>%s</strong> blocked user found.'),
                    $this->_('<strong>%s</strong> blocked users found.')
                ), $count); ?>

            <?php if ($this->paginator->getPages()->totalItemCount > 1) { ?>
                <?php echo sprintf(
                    $this->_('Showing results <strong>%s</strong> to <strong>%s</strong>'),
                    $this->paginator->getPages()->firstItemNumber,
                    $this->paginator->getPages()->lastItemNumber); ?>
            <?php } ?>
        </caption>
        <?php if ($this->paginator->getPages()->totalItemCount) { ?>
            <thead class="thead-light">
            <tr>
                <th><?php echo $this->_('Type / Value'); ?></th>
                <?php if ($inAdmin) { ?>
                    <th class="size-mini"><?php echo $this->_('Blocked By'); ?></th>
                <?php } ?>
                <th class="size-small"><?php echo $this->_('Actions'); ?></th>
                <th class="size-large"><?php echo $this->_('Reason'); ?></th>
                <th class="size-small"><?php echo $this->_('Date'); ?></th>
                <th class="size-actions"><?php echo $this->_('Actions'); ?></th>
            </tr>
            </thead>
        <?php } ?>
        <tbody>
        <?php
        /** @var \Ppb\Db\Table\Row\BlockedUser $blockedUser */
        foreach ($this->paginator as $blockedUser) {
            ?>
            <tr>
                <td>
                    <div><span class="badge badge-info"><?php echo $this->blockStatus($blockedUser)->blockType(); ?></span></div>
                    <div><?php echo $blockedUser['value']; ?></div>
                </td>
                <?php if ($inAdmin) {
                    /** @var \Ppb\Db\Table\Row\User $user */
                    $user = $blockedUser->findParentRow('\Ppb\Db\Table\Users');
                    ?>
                    <td>
                        <?php echo (!empty($user['username'])) ?
                            '<em>' . $user['username'] . '</em>' : '<span class="badge badge-primary">' . $this->_('Admin') . '</span>';
                        ?>
                    </td>
                <?php } ?>
                <td>
                    <?php echo $this->blockStatus()->blockedActions(); ?>
                </td>
                <td>
                    <div>
                        <?php echo ($blockedUser['show_reason']) ?
                            '<span class="badge badge-success">' . $this->_('Displayed') . '</span>' :
                            '<span class="badge badge-warning">' . $this->_('Hidden') . '</span>'; ?>
                    </div>
                    <div>
                        <small><?php echo $this->renderText($blockedUser['block_reason'], true, 120); ?></small>
                    </div>
                </td>
                <td>
                    <?php echo $this->date($blockedUser['created_at'], true); ?>
                </td>
                <td>
                    <a class="btn btn-secondary mb-1"
                       href="<?php echo $this->url(array('action' => 'edit-blocked-user', 'id' => $blockedUser['id']), null, true); ?>"
                       title="<?php echo $this->_('Edit Blocked User'); ?>">
                        <span data-feather="folder"></span>
                        <?php echo $this->_('Edit'); ?>
                    </a>
                    <a class="btn btn-danger mb-1 confirm-box"
                       href="<?php echo $this->url(array('action' => 'delete-blocked-user', 'id' => $blockedUser['id']),
                           null, true); ?>"
                       title="<?php echo $this->_('Delete Blocked User'); ?>"
                       data-message="<?php echo $this->_('Are you sure you want to delete this blocked user?'); ?>">
                        <span data-feather="x"></span>
                        <?php echo $this->_('Delete'); ?>
                    </a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<?php echo $this->pagination($this->paginator, 'sliding', 'partials/pagination.phtml'); ?>

