<?php
/**
 * @version 8.0 [rev.8.0.04]
 */

$headlineButtons = null;

$headlineButtons .= '<a class="btn btn-outline-secondary" '
    . 'href="' . $this->url(array('action' => 'add-voucher')) . '">'
    . $this->_('Create Voucher') . '</a>';

$this->setGlobal('headlineButtons', $headlineButtons);
?>
<nav class="navbar p-0 mb-4">
    <form class="form-inline ml-auto"
          action="<?php echo $this->url(null, null, true, array('code', 'submit')); ?>"
          method="get">
        <div class="form-group mr-1">
            <?php echo $this->formElement('text', 'code', $this->code)
                ->setAttributes(array('placeholder' => $this->_('Voucher Code'), 'class' => 'form-control input-default'))
                ->render();
            ?>
        </div>
        <?php echo $this->formElement('submit', 'submit', 'Search')
            ->setAttributes(array('class' => 'btn btn-secondary'))
            ->render();
        ?>
    </form>
</nav>

<div class="table-responsive">
    <table class="table table-hover">
        <caption>
            <?php echo sprintf(
                $this->pluralize(
                    $count = $this->paginator->getPages()->totalItemCount,
                    $this->_('<strong>%s</strong> voucher found.'),
                    $this->_('<strong>%s</strong> vouchers found.')
                ), $count); ?>

            <?php if ($this->paginator->getPages()->totalItemCount > 1) { ?>
                <?php echo sprintf(
                    $this->_('Showing results <strong>%s</strong> to <strong>%s</strong>'),
                    $this->paginator->getPages()->firstItemNumber,
                    $this->paginator->getPages()->lastItemNumber); ?>
            <?php } ?>
        </caption>
        <?php if ($this->paginator->getPages()->totalItemCount) { ?>
            <thead class="thead-light">
            <tr>
                <th class="size-medium"><?php echo $this->_('Name'); ?></th>
                <th class="size-medium"><?php echo $this->_('Code'); ?></th>
                <th><?php echo $this->_('Details'); ?></th>
                <th class="size-actions"><?php echo $this->_('Actions'); ?></th>
            </tr>
            </thead>
        <?php } ?>
        <tbody>
        <?php
        /** @var \Ppb\Db\Table\Row\Voucher $voucher */
        foreach ($this->paginator as $voucher) {
            ?>
            <tr>
                <td>
                    <?php echo $voucher['name']; ?>
                </td>
                <td>
                    <?php echo $voucher['code']; ?>
                </td>
                <td>
                    <dl class="dl-variable">
                        <dt>
                            <span><?php echo $this->_('Reduction'); ?></span>
                        </dt>
                        <dd>
                            <?php echo ($voucher['reduction_type'] == 'percent') ?
                                \Cube\Locale\Format::getInstance()->numericToLocalized($voucher['reduction_amount']) . '%' :
                                $this->amount($voucher['reduction_amount']); ?>
                        </dd>

                        <?php if ($voucher['expiration_date']) { ?>
                            <dt>
                                <span><?php echo $this->_('Expires'); ?></span>
                            </dt>
                            <dd>
                                <?php echo $this->date($voucher['expiration_date']); ?>
                            </dd>
                        <?php } ?>
                        <?php if ($voucher['uses_remaining'] !== null) { ?>
                            <dt>
                                <span><?php echo $this->_('Uses Remaining'); ?></span>
                            </dt>
                            <dd>
                                <?php echo $voucher['uses_remaining']; ?>
                            </dd>
                        <?php } ?>
                        <?php if ($voucher['assigned_listings'] != null) { ?>
                            <dt>
                                <span><?php echo $this->_('Assigned to Listings'); ?></span>
                            </dt>
                            <dd>
                                <?php echo $voucher['assigned_listings']; ?>
                            </dd>
                        <?php } ?>
                    </dl>
                </td>
                <td>
                    <a class="btn btn-secondary mb-1"
                       href="<?php echo $this->url(array('action' => 'edit-voucher', 'id' => $voucher['id']), null, true); ?>"
                       title="<?php echo $this->_('Edit Voucher'); ?>">
                        <span data-feather="folder"></span>
                        <?php echo $this->_('Edit'); ?>
                    </a>
                    <a class="btn btn-danger mb-1 confirm-box"
                       href="<?php echo $this->url(array('action' => 'delete-voucher', 'id' => $voucher['id']),
                           null, true); ?>"
                       title="<?php echo $this->_('Delete Voucher'); ?>"
                       data-message="<?php echo $this->_('Are you sure you want to delete this voucher?'); ?>">
                        <span data-feather="x"></span>
                        <?php echo $this->_('Delete'); ?>
                    </a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<?php echo $this->pagination($this->paginator, 'sliding', 'partials/pagination.phtml'); ?>

