<?php
/**
 * @version 8.0 [rev.8.0.01]
 */
?>

<?php if ($this->headline || $this->headlineButtons) { ?>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h4 class="mb-0"><?php echo $this->headline; ?></h4>

        <?php if ($this->headlineButtons) { ?>
            <div class="btn-toolbar">
                <?php echo $this->headlineButtons; ?>
            </div>
        <?php } ?>
    </div>
<?php } ?>

