<?php
/**
 * @version 8.0 [rev.8.0.03]
 */
/** @var \Ppb\Db\Table\Row\User $user */

$this->userDetails($user);

$headlineButtons = null;

$headlineButtons .= '<a class="btn btn-outline-secondary" '
    . 'href="' . $this->url(array('action' => 'add-address')) . '">'
    . $this->_('Add Address') . '</a>';

$this->setGlobal('headlineButtons', $headlineButtons);
?>

<div class="table-responsive">
    <table class="table table-hover">
        <caption>
            <?php echo sprintf(
                $this->pluralize(
                    $count = $this->paginator->getPages()->totalItemCount,
                    $this->_('<strong>%s</strong> address found in your address book.'),
                    $this->_('<strong>%s</strong> addresses found in your address book.')
                ), $count); ?>

            <?php if ($this->paginator->getPages()->totalItemCount > 1) { ?>
                <?php echo sprintf(
                    $this->_('Showing results <strong>%s</strong> to <strong>%s</strong>'),
                    $this->paginator->getPages()->firstItemNumber,
                    $this->paginator->getPages()->lastItemNumber); ?>
            <?php } ?>
        </caption>
        <?php if ($this->paginator->getPages()->totalItemCount) { ?>
            <thead class="thead-light">
            <tr>
                <th><?php echo $this->_('Address'); ?></th>
                <th class="size-small"><?php echo $this->_('Actions'); ?></th>
            </tr>
            </thead>
        <?php } ?>
        <tbody>
        <?php
        /** @var \Ppb\Db\Table\Row\UserAddressBook $address */
        foreach ($this->paginator as $address) {
            ?>

            <tr <?php echo ($address->isPrimary()) ? 'class="table-primary"' : ''; ?>>
                <td>
                    <?php echo $this->userDetails()->setAddress($address['id'])->displayFullAddress(); ?>

                    <?php if (!$address->isPrimary()) { ?>
                        <div class="mt-1">
                            <a class="btn btn-sm btn-primary confirm-box"
                               href="<?php echo $this->url(array('action' => 'primary-address', 'id' => $address['id'])); ?>"
                               title="<?php echo $this->_('Set as Primary'); ?>"
                               data-message="<?php echo $this->_('Are you sure you want to set this address as your primary address?'); ?>">
                                <span data-feather="at-sign"></span>
                                <?php echo $this->_('Set as Primary'); ?>
                            </a>
                        </div>
                    <?php } ?>
                </td>
                <td>
                    <?php if ($address->canEdit()) { ?>
                        <a class="btn btn-secondary mb-1"
                           href="<?php echo $this->url(array('action' => 'edit-address', 'id' => $address['id']), null, true); ?>"
                           title="<?php echo $this->_('Edit Address'); ?>">
                            <span data-feather="folder"></span>
                            <?php echo $this->_('Edit'); ?>
                        </a>
                    <?php } ?>
                    <?php if ($address->canDelete()) { ?>
                        <a class="btn btn-danger mb-1 confirm-box"
                           href="<?php echo $this->url(array('action' => 'delete-address', 'id' => $address['id']),
                               null, true); ?>"
                           title="<?php echo $this->_('Delete Address'); ?>"
                           data-message="<?php echo $this->_('Are you sure you want to delete this address from the address book?'); ?>">
                            <span data-feather="x"></span>
                            <?php echo $this->_('Delete'); ?>
                        </a>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<?php echo $this->pagination($this->paginator, 'sliding', 'partials/pagination.phtml'); ?>

