<?php
/**
 * @version 8.2 [rev.8.2.01]
 */
$this->statistics()->setAdmin(true);
?>

<div class="container px-0 ml-0">
    <div class="card-columns">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <div><?php echo $this->_('Users'); ?></div>
                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'users', 'action' => 'browse', 'view' => 'site')); ?>"
                   class="text-secondary" title="<?php echo $this->_('Users Management'); ?>">
                    <span data-feather="chevrons-right"></span></a>
            </div>

            <div class="card-body">
                <h5 class="card-title text-info">
                    <?php echo sprintf(
                        $this->pluralize(
                            $count = $this->statistics()->countUsers(),
                            $this->_('%s Registered User'),
                            $this->_('%s Registered Users')
                        ), $count); ?>
                </h5>

                <p class="card-text">
                    <?php echo sprintf(
                        $this->pluralize(
                            $count = $this->statistics()->countUsers(array('days' => 30)),
                            $this->_('%s user has registered in the last 30 days.'),
                            $this->_('%s users have registered in the last 30 days.')
                        ), $count); ?>
                </p>
                <?php
                if ($count = $this->statistics()->countUsers(array('awaiting_approval' => true))) { ?>
                    <p class="card-text">
                        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'users', 'action' => 'browse', 'view' => 'site', 'filter' => 'awaiting_approval')); ?>"
                           class="text-danger">
                            <?php echo sprintf(
                                $this->pluralize(
                                    $count,
                                    $this->_('%s account awaiting approval.'),
                                    $this->_('%s accounts awaiting approval.')
                                ), $count); ?>
                        </a>
                    </p>
                <?php } ?>
            </div>
        </div>

        <?php if ($this->settings['enable_auctions']) { ?>
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div><?php echo $this->_('Auctions'); ?></div>
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'listings', 'action' => 'browse', 'listing_type' => 'auction', 'filter' => 'open')); ?>"
                       class="text-secondary" title="<?php echo $this->_('Auctions Management'); ?>"><span
                                data-feather="chevrons-right"></span></a>
                </div>

                <div class="card-body">
                    <h5 class="card-title text-success">
                        <?php echo sprintf(
                            $this->pluralize(
                                $count = $this->statistics()->countListings(array('filter' => array('active', 'open'), 'listing_type' => 'auction')),
                                $this->_('%s Open Auction'),
                                $this->_('%s Open Auctions')
                            ), $count); ?>
                    </h5>

                    <p class="card-text">
                        <?php echo sprintf(
                            $this->pluralize(
                                $count = $this->statistics()->countListings(array('filter' => array('active', 'open'), 'listing_type' => 'auction', 'closing' => date('Y-m-d H:i:s', strtotime("+3 days")))),
                                $this->_('%s auction ending in the next 3 days.'),
                                $this->_('%s auctions ending in the next 3 days.')
                            ), $count); ?>
                    </p>
                    <p class="card-text">
                        <?php echo sprintf(
                            $this->pluralize(
                                $count = $this->statistics()->countListings(array('listing_type' => 'auction')),
                                $this->_('%s auction found.'),
                                $this->_('%s total auctions found.')
                            ), $count); ?>
                    </p>

                </div>
            </div>
        <?php } ?>

        <?php if ($this->settings['enable_products']) { ?>
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div><?php echo $this->_('Products'); ?></div>
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'listings', 'action' => 'browse', 'listing_type' => 'product', 'filter' => 'open')); ?>"
                       class="text-secondary" title="<?php echo $this->_('Products Management'); ?>"><span
                                data-feather="chevrons-right"></span></a>
                </div>

                <div class="card-body">
                    <h5 class="card-title text-primary">
                        <?php echo sprintf(
                            $this->pluralize(
                                $count = $this->statistics()->countListings(array('filter' => 'open', 'listing_type' => 'product')),
                                $this->_('%s Open Product'),
                                $this->_('%s Open Products')
                            ), $count); ?>
                    </h5>
                    <p class="card-text">
                        <?php echo sprintf(
                            $this->pluralize(
                                $count = $this->statistics()->countListings(array('listing_type' => 'product')),
                                $this->_('%s product found.'),
                                $this->_('%s total products found.')
                            ), $count); ?>
                    </p>
                </div>
            </div>
        <?php } ?>

        <?php if ($this->settings['enable_classifieds']) { ?>
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div><?php echo $this->_('Classifieds'); ?></div>
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'listings', 'action' => 'browse', 'listing_type' => 'classified', 'filter' => 'open')); ?>"
                       class="text-secondary" title="<?php echo $this->_('Classifieds Management'); ?>"><span
                                data-feather="chevrons-right"></span></a>
                </div>

                <div class="card-body">
                    <h5 class="card-title text-danger">
                        <?php echo sprintf(
                            $this->pluralize(
                                $count = $this->statistics()->countListings(array('filter' => 'open', 'listing_type' => 'classified')),
                                $this->_('%s Open Classified'),
                                $this->_('%s Open Classifieds')
                            ), $count); ?>
                    </h5>
                    <p class="card-text">
                        <?php echo sprintf(
                            $this->pluralize(
                                $count = $this->statistics()->countListings(array('listing_type' => 'classified')),
                                $this->_('%s classified found.'),
                                $this->_('%s total classifieds found.')
                            ), $count); ?>
                    </p>
                </div>
            </div>
        <?php } ?>

        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <div><?php echo $this->_("Who's Online"); ?></div>
                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'tools', 'action' => 'users-statistics')); ?>"
                   class="text-secondary" title="<?php echo $this->_('Online Users'); ?>"><span
                            data-feather="chevrons-right"></span></a>
            </div>

            <div class="card-body">
                <h5 class="card-title text-dark">
                    <?php echo sprintf(
                        $this->pluralize(
                            $count = $this->statistics()->countOnlineUsers(array('minutes' => 3)),
                            $this->_('%s User Online'),
                            $this->_('%s Users Online')
                        ), $count); ?>
                </h5>

                <p class="card-text">
                    <?php echo sprintf(
                        $this->pluralize(
                            $count = $this->statistics()->countOnlineUsers(),
                            $this->_('%s visitor during the last hour.'),
                            $this->_('%s visitors during the last hour.')
                        ), $count); ?></p>
            </div>
        </div>

        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <div><?php echo $this->_("Newsletters"); ?></div>
                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'tools', 'action' => 'newsletters')); ?>"
                   class="text-secondary" title="<?php echo $this->_('Newsletters Management'); ?>"><span
                            data-feather="chevrons-right"></span></a>
            </div>

            <div class="card-body">
                <h5 class="card-title text-danger">
                    <?php echo sprintf(
                        $this->pluralize(
                            $count = $this->statistics()->countNewsletterSubscribers(),
                            $this->_('%s Subscriber'),
                            $this->_('%s Subscribers')
                        ), $count); ?>
                </h5>

                <?php
                $lastNewsletterSentOn = $this->statistics()->lastNewsletterSentOn();
                if ($lastNewsletterSentOn !== null) { ?>
                    <p class="card-text"><?php echo sprintf($this->_('Last newsletter sent on %s.'), $this->date($lastNewsletterSentOn)); ?></p>
                <?php } ?>
            </div>
        </div>
    </div>

    <div class="mt-3">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h5><?php echo $this->_('Sales in the last 7 days'); ?></h5>

            <div class="btn-toolbar">
                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'listings', 'action' => 'sales')); ?>"
                   class="btn btn-outline-secondary"><?php echo $this->_('View All'); ?></a>
            </div>
        </div>

        <?php echo $this->action('browse', 'invoices', 'members', array('summary' => true, 'date_from' => date("Y-m-d H:i:s", strtotime("-1 week")))); ?>
    </div>
</div>