<?php
/**
 * @version 8.0 [rev.8.0.01]
 */
/**
 * MOD:- SELLERS CREDIT
 * MOD:- BANK TRANSFER
 */
?>

<form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>">
    <?php echo $this->form->hiddenElements; ?>

    <div class="table-responsive">
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th class="size-small">Payment Gateway</th>
                <th>Settings</th>
                <th class="size-mini">Site Fees</th>
                <th class="size-mini">Direct Payment</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $checkboxCounter = 0;
            foreach ((array)$this->form->getData() as $data) {
                ## -- ONE LINE :: ADD -- [ MOD:- SELLERS CREDIT ]
                if ($data['name'] != 'SellersCredit') {
                    ?>
                    <tr>
                        <td>
                        <img src="<?php echo $this->baseUrl . $data['logo_path']; ?>"
                             alt="<?php echo $data['name']; ?>">
                        </td>
                        <td>
                            <?php
                        ## -- START :: ADD -- [ MOD:- BANK TRANSFER ]
                        if ($data['name'] == 'BankTransfer') {
                            echo $this->action('bank-accounts', 'account', 'members');
                        }
                        else {
                        ## -- END :: ADD -- [ MOD:- BANK TRANSFER ]
                            /* @var \Cube\Form\Element $element */
                            foreach ($this->formElements as $element) {
                                if ($element['form_id'] == $data['name']) {

                                    $element = $this->form->getElement($element['id']);
                                    $label = $element->getLabel();
                                    $description = $element->getDescription();
                                    $elementName = $element->getName();

                                    if (isset($data[$elementName])) {
                                        $element->setData($data[$elementName]);
                                    }

                                    $element->setBrackets('[' . $data['id'] . ']')->setMultiple();

                                    echo $this->partial('partials/form-element.phtml', array('element' => $element));
                                }
                            ## -- ONE LINE :: ADD -- [ MOD:- BANK TRANSFER ]
                            }
                            } ?>
                        </td>
                        <td>
                            <?php echo $this->form->getElement('site_fees')
                                ->setData($data['site_fees'])
                                ->setBrackets('[' . $checkboxCounter . ']')
                                ->render(); ?>
                        </td>
                        <td>
                            <?php echo $this->form->getElement('direct_payment')
                                ->setData($data['direct_payment'])
                                ->setBrackets('[' . $checkboxCounter . ']')
                                ->render(); ?>
                            <?php echo $this->form->getElement('id')->setData($data['id'])->render(); ?>
                        </td>
                    </tr>
                    <?php $checkboxCounter++; ?>
                <?php
                ## -- ONE :: ADD -- [ MOD:- SELLERS CREDIT ]
                }
            } ?>
            <tr>
                <td colspan="4"><?php echo $this->form->getElement('submit')->render(); ?></td>
            </tr>
            </tbody>
        </table>
    </div>
</form>