<?php
/**
 * @version 8.0 [rev.8.0.02]
 */
?>
<table class="table table-hover">
    <caption>
        <?php echo $this->_('Leave feedback for the selected listings.'); ?>
    </caption>
    <thead class="thead-light">
    <tr>
        <th><?php echo $this->_('Listing Details'); ?></th>
        <th class="size-small">
            <?php echo $this->_('To'); ?>
        </th>
    </tr>
    </thead>
    <tbody>
    <?php
    /** @var \Ppb\Db\Table\Row\Reputation $reputation */
    foreach ($this->rowset as $reputation) {
        $listingLink = null;
        $listingName = null;
        $listingImage = null;

        if ($reputation['sale_listing_id'] != null) {
            /** @var \Ppb\Db\Table\Row\Listing $listing */
            $saleListing = $reputation->findParentRow('\Ppb\Db\Table\SalesListings');
            $listing = null;
            if ($saleListing) {
                $listing = $saleListing->findParentRow('\Ppb\Db\Table\Listings');
            }

            if ($listing) {
                $listingLink = $listing->link();
                $listingName = $listing['name'];
                $listingImage = $listing->getMainImage();
            }
        }

        $user = $reputation->findParentRow('\Ppb\Db\Table\Users', 'User');

        $userType = null;
        switch ($reputation['reputation_type']) {
            case \Ppb\Service\Reputation::SALE:
                $userType = 'Seller';
                break;
            case \Ppb\Service\Reputation::PURCHASE:
                $userType = 'Buyer';
                break;
        }

        if (empty($listingName)) {
            $listingName = ($reputation['listing_name']) ? $reputation['listing_name'] : $this->_('Listing Deleted');
        }
        ?>
        <tr>
            <td>
                <div class="media">
                    <?php echo $this->thumbnail($listingImage, 128, true,
                        array('alt' => $listingName, 'class' => 'mr-3 img-sm')); ?>

                    <div class="media-body">
                        <h6 class="mt-0">
                            <?php if ($listingLink) { ?>
                                <a href="<?php echo $this->url($listingLink); ?>">
                                    <?php echo $listingName; ?>
                                </a>
                                <?php
                            }
                            else {
                                ?>
                                <em><?php echo $listingName; ?></em>
                            <?php } ?>
                        </h6>
                    </div>
                </div>
            </td>
            <td>
                <?php echo '<strong>' . $this->_($userType) . '</strong><br>' . $this->userDetails()->setUser($user)->display(); ?>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>

<?php echo $this->form; ?>
